apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - name: db
      image: postgres
      ports:
         - containerPort: 5432
root@em7admin:/home/em7admin# ^C
root@em7admin:/home/em7admin# cat namespacesManifest.yaml
apiVersion: v1
kind: Namespace
metadata:
    name: dev
    labels:
        name: development
---
apiVersion: v1
kind: Namespace
metadata:
    name: test
    labels:
        name: testing
---
apiVersion: v1
kind: Namespace
metadata:
    name: prod
    labels:
        name: production
